version: '3.8'

services:
  backend:
    image: freelancekks/newsaggregator:latest
    container_name: newsaggregator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    image: freelancekks/news-aggregator-frontend:latest
    container_name: news-aggregator-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend